name: "Bug report"
title: "bug: "
labels: ["bug"]
description: Report a bug in Keyman
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start
        
        Before you submit this bug report, have you searched other reports for this bug?
          https://github.com/keymanapp/keyman/issues?q=is%3Aopen+is%3Aissue+label%3Abug

        * If you find a matching issue, go ahead and add a comment on that issue.
        * If you find related issues, make sure you list them below.

        You may also wish to discuss your bug report with the Keyman community at:
          https://community.software.sil.org/c/keyman

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: "Reproduce the bug"
      description: "Write up the steps you took which triggered the bug. Be as precise as possible; you can paste screenshots and/or videos if you wish."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

