name: "Bug report"
title: "bug: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start
        
        Before you submit this bug report, have you searched other reports for this bug?
          https://github.com/keymanapp/keyman/issues?q=is%3Aopen+is%3Aissue+label%3Abug

        * If you find a matching issue, go ahead and add a comment on that issue.
        * If you find related issues, make sure you list them below.

        You may also wish to discuss your bug report with the Keyman community at:
          https://community.software.sil.org/c/keyman

        ### Desrcibe the bug

  - type: textarea
    id: description
    attributes:
      label: "A clear and concise description of what the bug is"
      required: true

  - type: markdown
    attributes:
      value: |
        ### Reproduce the bug

        Write up the steps you took which triggered the bug. Be as precise as possible;
        you can paste screenshots and/or videos if you wish. For example,

  - type: textarea
    id: repro
    attributes:
      label: "Steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

